name: Mobile CI (Flutter)

on:
  push:
    branches: [ main, 'feature/*', 'member-*/*', 'IT*/**' ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile/fixflow_mobile

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test
